name: Snyk Code

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: snyk/actions/setup@master

      - name: Snyk Code test
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
